channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - cython
  - matplotlib=3.2
  - pyamg
  - mayavi
  - pandas
  - openpyxl
  - scikit-image
  - scikit-learn
  - boto3
  - awscli
  - openjdk=8
  - pyqt
  - pyface
  - importlib_metadata  # required for pyface
  - importlib_resources  # required for pyface
  - traitsui
  - appdirs
  - pip:
    - --extra-index-url https://pypi.fury.io/dd8/
    - matplotlib-scalebar
    - simpleitk==1.2.0rc2.dev1162+g2a79d
    - javabridge==1.0.18.post21+g4526f53
    - python-bioformats==1.1.0
