channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - cython
  - matplotlib>=3.2,!=3.3.0,!=3.3.1
  - pyamg
  - mayavi
  - pandas
  - openpyxl
  - scikit-image
  - scikit-learn
  - boto3
  - awscli
  - openjdk=8
  - pyqt
  - pyface
  - importlib_metadata  # required for pyface
  - importlib_resources  # required for pyface
  - traitsui
  - appdirs
  - pip:
    - --extra-index-url https://pypi.fury.io/dd8/
    - matplotlib-scalebar
    - simpleitk==2.0.2rc2.dev785+g8ac4f
    - javabridge==1.0.19.post4+gbebed64
    - python-bioformats==4.0.5.post2+g51eb88a
