
volcanoPlot <- function(stats, meas, interaction, thresh=NULL, 
                        log.scale.x=TRUE) {
  # Generate a volcano plot.
  #
  # Args:
  #   stats: Data frame generated by \code{\link{filterStats}}.
  #   meas: Measurement to display in plot title.
  #   interaction: Interaction column name whose set of stats should be 
  #     displayed.
  #   thresh: Threshold as a 2-element array corresponding to the x and y 
  #     values, respectively, above which labels will be shown if both 
  #     condition is met. NA for either value will cause the threshold to 
  #     be ignored, or NA for the entire argument will ignore thresholding 
  #     all together.
  #   log.scale.x: True to scale x-axis by log10, first normalizing to 
  #     the minimum x-value before taking the log of the absolute value 
  #     to avoid negative log values, then returning to the original sign.
  
  x <- stats[[paste0(interaction, ".effect")]]
  num.x <- length(x)
  if (num.x < 1) {
    cat("no values found to generate volcano plot, skipping\n")
    return()
  }
  y <- stats[[paste0(interaction, ".logp")]]
  # weight size based on mean volume, replacing NaNs with a small num
  vol <- stats$Volume
  if (isTRUE(all.equal(vol, rep(0, num.x)))) {
    size <- rep(1, num.x)
  } else {
    vol[is.nan(vol) | vol == 0] <- 1
    size <- sqrt(vol / max(vol)) * 3
  }
  #print(data.frame(x, size))
  
  # point colors based on IDs of parents at the level generated for region 
  # IDs file, using a palette with color for each unique parent
  parents <- stats$Parent
  parents.unique <- unique(parents)
  parents.indices <- match(parents, parents.unique)
  colors <- viridis::viridis(length(parents.unique))
  colors_parents <- colors[parents.indices]
  
  # base plot -log p vs effect size
  if (log.scale.x) {
    # log scale x, rescaling so abs vals of x are >= 1 to get pos log vals 
    # and changing back to original sign
    x.neg <- x < 0
    x.norm <- x / min(abs(x))
    x.log <- log(abs(x.norm))
    x.log[x.neg] <- -1 * x.log[x.neg]
    print(data.frame(x, x.norm, x.neg, x.log, y))
    x <- x.log
  }
  x.max <- max(abs(x))
  if (is.element(meas, names(kMeasNames))) {
    title <- kMeasNames[[meas]]
  } else {
    title <- paste(meas, "Differences for", interaction)
  }
  plot(
    x, y, xlim=c(-1 * x.max, x.max), 
    main=title, xlab="Effects", 
    ylab="-log10(p)", type="p", las=1, pch=16, cex=size, col=colors_parents)
  # vertical line to denote x = 0
  abline(v=0, lty="dashed", col=gray(0.5, 0.5))
  
  # label points
  x.lbl <- x
  y.lbl <- y
  lbls <- stats$RegionAbbr
  if (!is.null(thresh)) {
    # limit labels only to those within all thresholds, ignoring NAs
    show.lbl <- abs(x) > 0
    if (!is.na(thresh[1])) show.lbl <- abs(x) > thresh[1] & show.lbl
    if (!is.na(thresh[2])) show.lbl <- y > thresh[2] & show.lbl
    x.lbl <- x[show.lbl]
    y.lbl <- y[show.lbl]
    lbls <- lbls[show.lbl]
  }
  if (length(lbls) > 0) {
    # place text labels; "text" has full overlap, "thigmophobe.labels" and 
    # "pointLabels" have varying degrees of overlap, and "addTextLabels" has 
    # the least overlap
    #text(x.lbl, y.lbl, label=lbls, cex=0.2)
    #thigmophobe.labels(x.lbl, y.lbl, label=lbls, cex=0.2)
    #pointLabel(x.lbl, y.lbl, label=lbls, cex=0.2)
    addTextLabels::addTextLabels(x.lbl, y.lbl, label=lbls, cex=0.5, lwd=0.2)
  }
  
  # write to PDF file
  dev.print(
    pdf, file=paste("../plot_volcano", meas, paste0(interaction, ".pdf"), 
                    sep="_"))
}
