channels:
  - defaults
dependencies:
  - python=3.6
  - pip
  - cython
  - matplotlib
  - pyamg
  - pandas
  - scikit-image
  - scikit-learn
  - appdirs
  - tifffile
  - zarr
  - pip:
    - --extra-index-url https://pypi.fury.io/dd8/
    - simpleitk==2.0.2rc2.dev785+g8ac4f
    - javabridge==1.0.19.post4+gbebed64
    - python-bioformats==4.0.5.post2+g51eb88a
