channels:
  - defaults
dependencies:
  - python=3.6
  - pip
  - cython
  - matplotlib
  - pyamg
  - pandas
  - scikit-image
  - scikit-learn
  - appdirs
  - pip:
    - --extra-index-url https://pypi.fury.io/dd8/
    - simpleitk==1.2.0rc2.dev1162+g2a79d
    - javabridge==1.0.18.post21+g4526f53
    - python-bioformats==1.1.0
